add training on val
sham1lk/ship-classification pull request #2
Opened 2023-12-16 09:52 UTC by sham1lk

2023-12-16 14:59 UTC, pyaiveoleg requested changes
По ноутбуку вопросов нет
По псевдолейблингу: подход реализован правильно, но от "двумерности" датасета лучше избавиться

2023-12-16 14:59 UTC, pyaiveoleg commented on model.py
> +            x, y = batch
А что тут происходит? :)

2023-12-16 14:59 UTC, pyaiveoleg commented on train.py
> +        )
Нам тут нужен class ConcatenateDatasets, который на вход принимает несколько датасетов и выдает их в нужном порядке, тогда код станет чуточку аккуратнее

2023-12-22 20:07 UTC, sham1lk commented on model.py
> +            x, y = batch
так как использовал два даталоудера pytorch lightning  возвращает лист Бачей, объединил их в один)

2023-12-22 21:06 UTC, merged

2023-12-22 21:08 UTC, sham1lk commented on model.py
> +            x, y = batch
убрал, добавил ConcatenateDatasets

2023-12-22 21:08 UTC, sham1lk commented on train.py
> +        )
добавил ConcatenateDatasets

2023-12-22 21:09 UTC, sham1lk commented
> По ноутбуку вопросов нет По псевдолейблингу: подход реализован правильно, но от "двумерности" датасета лучше избавиться

Случайно смержил ветки(

2023-12-22 21:10 UTC, sham1lk commented on model.py
> +            x, y = batch
изменения тут, https://github.com/sham1lk/ship-classification/pull/3/files, случайно смержил